lab15/models/doctor.py
from app import db

class Doctor(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    specialty = db.Column(db.String(200))

    def __repr__(self):
        return f"<ID {self.id} Doctor {self.name} Specialty {self.specialty}>"

lab15/blueprints/doctors_routes.py
from flask import Blueprint, request, render_template, redirect, url_for, jsonify
from blueprints.Forms import *
import sqlite3

DB_PATH = 'site.db'

def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

doctor_bp = Blueprint('doctor', __name__)


@doctor_bp.route('/')
def IndexDoctor():
    conn = get_conn()
    conn.execute('''CREATE TABLE IF NOT EXISTS doctor (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        specialty TEXT
    )''')
    cur = conn.execute('SELECT id, name, specialty FROM doctor')
    rows = [dict(r) for r in cur.fetchall()]
    conn.close()
    return render_template('Doctors/index.html', list=rows)


@doctor_bp.route('/Create', methods=['GET', 'POST'])
def CreateDoctor():
    form = DoctorForm()
    if request.method == 'POST':
        name = request.form.get('name')
        specialty = request.form.get('specialty')
        conn = get_conn()
        conn.execute('INSERT INTO doctor (name,specialty) VALUES (?,?)', (name, specialty))
        conn.commit()
        conn.close()
        return redirect(url_for('doctor.IndexDoctor'))
    return render_template('Doctors/create.html', form = form)

@doctor_bp.route('/Edit/<int:id>', methods=['GET', 'POST'])
def EditDoctor(id):
    conn = get_conn()
    cur = conn.execute('SELECT id,name,specialty FROM doctor WHERE id=?', (id,))
    row = cur.fetchone()
    conn.close()
    if not row:
        return jsonify({'error': 'not found'}), 404
    return jsonify({'id': row['id'], 'name': row['name'], 'specialty': row['specialty'], 'MESSAGE':'!!!!!!! PHOTO NOT GIVEN !!!!!!!!'})


@doctor_bp.route('/Details/<int:id>', methods=['GET'])
def DetailsDoctor(id):
    conn = get_conn()
    cur = conn.execute('SELECT id,name,specialty FROM doctor WHERE id=?', (id,))
    row = cur.fetchone()
    conn.close()
    temp = DoctorForm(data=dict(row))
    return render_template('Doctors/details.html', data = temp)

@doctor_bp.route('/Delete/<int:id>', methods=['POST'])
def DeleteDoctor(id):
    conn = get_conn()
    conn.execute('DELETE FROM doctor WHERE id = ?', (id,))
    conn.commit()
    conn.close()
    return redirect(url_for('doctor.IndexDoctor'))

lab15/templates/Doctors/create.html
{% extends "layout.html" %}

{% block title %}Create{% endblock %}

{% block content %}
    <h1 class="margin-b-0 bold-sp">Create</h1>
    <h3 class="margin-txxs bold-s">Doctor</h3>
    <hr>
    <form method="POST" class="font-size-s margin-ts margin-bxs">
        {{ form.hidden_tag() }}
        <div class="margin-bxs">
            {{form.name.label(class="bold margin-bxxs font-size-s")}} <br>
            {{form.name(class="width-m")}} <br>
        </div>
        <div class="margin-bxs">
            {{form.specialty.label(class="bold margin-bxxs font-size-s")}} <br>
            {{form.specialty(class="width-m")}} <br>
        </div>
        <button type="submit" class="bg-white border-xs-s-black width-xsp height-xs">Create</button>
    </form>
    <div class="margin-0 margin-bxs">
        <a href="{{url_for('doctor.IndexDoctor')}}" class="hlink-clean font-blue">Back to List</a>
    </div>
{% endblock %}

lab15/templates/Doctors/details.html
{% extends "layout.html" %}

{% block title %}Details{% endblock %}

{% block content %}
    <h1 class="margin-b-0 bold-sp">Details</h1>
    <h3 class="margin-txxs bold-s">Doctor</h3>
    <hr>
    <div class=" padding-lm margin-bxs font-size-s">
        <div class="flex-row gap-s">
            <div class="width-xsm text-right"> {{data.name.label(class="bold")}}</div>
            <div class="text-left">{{data.name.data}}</div>
        </div>
        <div class="flex-row gap-s">
            <div class="width-xsm text-right bold">{{data.specialty.label(class="bold")}}</div>
            <div class="text-left">{{data.specialty.data}}</div>            
        </div>
    </div>
    <div margin-0 margin-bxs>
        <a href="{{url_for('doctor.EditDoctor', id = data.id.data)}}" class="hlink-clean font-blue">Edit</a> | 
        <a href="{{url_for('doctor.IndexDoctor')}}" class="hlink-clean font-blue">Back to List</a>
    </div>
{% endblock %}

lab15/templates/Doctors/index.html
{% extends "layout.html" %}


{% block title %}Index{% endblock %}

{% block content %}
    <h1 class="margin-bxxs">Index</h1>
    <a href="{{url_for('doctor.CreateDoctor')}}" class="hlink-clean font-blue">Create New</a>
    <table class="width-full font-size-s margin-txs border-collapse">
        <thead class="width-full border-bxs-s-black">
            <tr class="width-full text-left">
                <th class="bold font-size-s padding-lxs width-sm">Name</th>
                <th class="bold font-size-s padding-lxs width-sm">Specialty</th>
            </tr>
        </thead>
        <tbody>
            {% for entry in list %}
            <tr>
                <td class="padding-lxs">{{entry.name}}</td>
                <td class="padding-lxs">{{entry.specialty}}</td>
                <td class="padding-lxs">
                    <ul class="flex-row ls-none ">
                        <li><a href="{{url_for('doctor.EditDoctor', id=entry.id)}}" class="hlink-clean color-blue">Edit</a></li> &nbsp;|&nbsp;
                        <li><a href="{{url_for('doctor.DetailsDoctor', id=entry.id)}}" class="hlink-clean color-blue wrap">Details</a></li> &nbsp;|&nbsp;
                        <li>
                            <form method="post" action="{{url_for('doctor.DeleteDoctor', id=entry.id)}}">
                                <button style="background:none; border:none; color:blue; cursor:pointer; padding:0;">Delete</button>
                            </form>
                        </li>
                    </ul>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}