lab14/app.py
from flask import Flask, redirect, render_template
from blueprints import ConnectRoutings

app = Flask(__name__)
app.config['SECRET_KEY'] = '123456'
ConnectRoutings(app)

@app.route('/')
def startapp():
    return redirect('/Index')

@app.route('/Index')
def index():
    return render_template('index.html')   

if __name__ == '__main__':
    app.run(debug=True)

lab14/blueprints/Forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, RadioField, SelectField as DropDownField, PasswordField, EmailField, IntegerField
from wtforms.validators import DataRequired, Length, Email, EqualTo, NumberRange
import calendar

class TextBoxForm(FlaskForm):
    text = StringField('Text')

class TextAreaForm(FlaskForm):
    text = TextAreaField('Text')

class CheckBoxForm(FlaskForm):
    IsSelected = BooleanField('IsSelected')

class RadioForm(FlaskForm):
    Months = RadioField('Months', choices= [month for month in calendar.month_name if month])

class DropDownForm(FlaskForm):
    Months = DropDownField('Months', choices=[month for month in calendar.month_name if month])

ListBoxField = DropDownField
class ListBoxForm(FlaskForm):
    Months = ListBoxField()


SelectField = ListBoxField
class SignUpForm(FlaskForm):
    firstname = StringField('First name', validators=[DataRequired(), Length(max=100)], render_kw={"required": "required"})
    lastname = StringField('Last name', validators=[DataRequired()], render_kw={"required": "required"})
    day = SelectField('Day', choices=[(str(i), str(i)) for i in range(1, 32)], validators=[DataRequired()])
    month = SelectField('Months', choices=[month for month in calendar.month_name if month], validators=[DataRequired()])
    year = SelectField('Year', choices=[(str(i), str(i)) for i in range(1900, 2026)], validators=[DataRequired()])
    gender = RadioField('Gender', validators=[DataRequired()], choices = [('m', 'Male'),('f', 'Female')], render_kw={"required": "required"})
    email = EmailField('Email', validators=[Email(), DataRequired(), Length(max=100)], render_kw={"required": "required"})
    password =  PasswordField('Password', validators=[DataRequired()], render_kw={"required": "required"})
    confirmpassword = PasswordField('Confirm password', validators=[DataRequired(), EqualTo('password')], render_kw={"required": "required"})


class ResetForm(FlaskForm):
    email = EmailField('Email', validators=[Email(), DataRequired(), Length(max=100)], render_kw={"required": "required"})
    code = IntegerField('Code', validators=[DataRequired()])

lab14/blueprints/__init__.py
from flask import Flask
from blueprints.user_routes import user_bp
from blueprints.login_routes import login_bp

def ConnectRoutings(appname):
    appname.register_blueprint(user_bp, url_prefix='/Controls')
    appname.register_blueprint(login_bp, url_prefix='/Mockups')
    

lab14/blueprints/login_routes.py
from flask import Blueprint, request, render_template, redirect, url_for, session, jsonify
from blueprints.Forms import *
import random

login_bp = Blueprint('login', __name__)

@login_bp.route('/SignUp', methods=['GET', 'POST'])
def SignUp():
    form = SignUpForm()
    if form.validate_on_submit():
        session['login'] = {
            'firstname' : form.firstname.data,
            'lastname' : form.lastname.data,
            'birthday' : f'{form.day.data}  {form.month.data} {form.year.data}', 
            'gender' : form.gender.data,
            'email' : form.email.data,
            'password' : form.password.data,
        }
        return redirect(url_for('login.SignUpCredentials'))
    return render_template('Mockups/SignUp.html', form=form)

@login_bp.route('/SignUpCredentials')
def SignUpCredentials():
    data = session.get('login')
    return render_template('Mockups/SignUpCredentials.html', data = data)

@login_bp.route('/Reset', methods = ['GET', 'POST'])
def ResetPassword():
    action = request.form.get("action")
    if request.method == "GET":
        form = ResetForm()
        return render_template('Mockups/Reset.html', form=form, rightcode = session.get("email_code"))
    elif request.method == "POST":
        if action == "send_code":
            code = str(random.randint(100000, 999999))
            session["email_code"] = code
            return jsonify(success=True)
        if action == "verify_code":
            if request.form.get("code") == session.get("email_code"):
                return jsonify(success=True)
        return jsonify(success=False)
        

lab14/blueprints/user_routes.py
from flask import Blueprint, render_template, request, jsonify
from blueprints.Forms import *

user_bp = Blueprint('user', __name__)

@user_bp.route('/')
def ControlsRoute():
    return render_template('Controls.html')

@user_bp.route('/TextBox', methods = ['GET', 'POST'])
def TextBoxRoute():
    form = TextBoxForm()
    if request.method == 'POST':
        return jsonify({'result': form.text.data})
    return render_template('Controls/TextBox.html', form = form)

@user_bp.route('/TextArea', methods = ['GET', 'POST'])
def TextAreaRoute():
    form = TextAreaForm()
    if request.method == 'POST':
        return jsonify({'result': form.text.data})
    return render_template('Controls/TextArea.html', form = form)

@user_bp.route('/CheckBox', methods = ['GET', 'POST'])
def CheckBoxRoute():
    form = CheckBoxForm()
    if request.method == 'POST':
        return jsonify({'result': form.IsSelected.data})
    return render_template('Controls/CheckBox.html', form = form)

@user_bp.route('/Radio', methods = ['GET', 'POST'])
def RadioRoute():
    form = RadioForm()
    if request.method == 'POST':
        return jsonify({'result': form.Months.data})
    return render_template('Controls/Radio.html', form = form)

@user_bp.route('/DropDownList', methods = ['GET', 'POST'])
def DropDownRoute():
    form = DropDownForm()
    if request.method == 'POST':
        return jsonify({'result': form.Months.data})
    return render_template('Controls/DropDownList.html', form = form)

@user_bp.route('/ListBox', methods = ['GET', 'POST'])
def ListBoxRoute():
    form = ListBoxForm()
    if request.method == 'POST':
        return jsonify({'result': form.Months.data})
    return render_template('Controls/ListBox.html', form = form)

lab14/templates/Controls.html
    {% extends "layout.html" %}

    <!DOCTYPE html>
    <html>
        <head>
            {% block title %}Controls{% endblock %}
            <link rel="stylesheet" href="../static/style.css">
        </head>
        <body>
            {% block content %}
            <h1>Controls</h1>
            <ul>
                <li><a href="{{url_for('user.TextBoxRoute')}}" class="hlink-clean font-blue">TextBox</a></li>
                <li><a href="{{url_for('user.TextAreaRoute')}}" class="hlink-clean font-blue">TextArea</a></li>
                <li><a href="{{url_for('user.CheckBoxRoute')}}"class="hlink-clean font-blue">CheckBox</a></li>
                <li><a href="{{url_for('user.RadioRoute')}}"class="hlink-clean font-blue">Radio</a></li>
                <li><a href="{{url_for('user.DropDownRoute')}}"class="hlink-clean font-blue">DropDownList</a></li>
                <li><a href="{{url_for('user.ListBoxRoute')}}"class="hlink-clean font-blue">ListBox</a></li>
            </ul>
            {% endblock %}
        </body>
    </html>

lab14/templates/index.html
{% extends "layout.html" %}

<!DOCTYPE html>
<html>
    <head>
        {% block title %}Home Page{% endblock %}
        <link rel="stylesheet" href="../static/style.css">
    </head>
    <body>
        {% block content%}
            <h1>Multi-staged forms</h1>
            <ul>
                <li><a href="{{url_for('login.ResetPassword')}}" class="hlink-clean font-blue">Password Reset</a></li>
                <li><a href="{{url_for('login.SignUp')}}" class="hlink-clean font-blue">Sign Up</a></li>
            </ul>
        {% endblock %}
    </body>
</html>

lab14/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - Backend4</title>
    <link rel="stylesheet" href="../static/style.css">
</head>
<body class="margin-0">
    <nav>
        <div class="flex-row bg-black margin-0 center-h height-s">
            <h3 class="font-white padding-ls bold">Backend4</h4>
            <ul class="flex-row ls-none center-vh gap-s">
                <li><a href="{{url_for('startapp')}}" class="hlink-clean font-white font-size-s">Home</a></li>
                <li><a href="{{url_for('login.SignUp')}}" class="hlink-clean font-white font-size-s">Mockups</a></li>
                <li><a href="{{url_for('user.ControlsRoute')}}" class="hlink-clean font-white font-size-s">Controls</a></li>
            </ul>
        </div>
    </nav>
    <main class="padding-lrs">
        {% block content %}{% endblock %}
        <hr>
        <span>©2025 - Backend4</span>
    </main>

</body>
</html>